apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefiletest-aksapac3
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: azurefile
  resources:
    requests:
      storage: 5Gi